#!/bin/bash

# Path to the log file
LOG_FILE="/tmp/log"

# Read the trap information from standard input
read host
read ip
vars=""

# Read each OID and its corresponding value
while read oid val
do
    # Format the OID and value
    formatted_oid="${oid%.*}.${oid##*.}"
    formatted_val=$(echo "$val" | awk '{gsub(/"/, "\\\""); print}')

    # Append the OID and value to the vars string
    vars+="$formatted_oid = $formatted_val"$'\n'
done

# Format the trap information
formatted_trap="Trap: $1"$'\n'
formatted_host="Host: $host"$'\n'
formatted_ip="IP: $ip"$'\n'

# Print the trap information and variables to the log file
echo "$formatted_trap" >> "$LOG_FILE"
echo "$formatted_host" >> "$LOG_FILE"
echo "$formatted_ip" >> "$LOG_FILE"
echo "Variables:" >> "$LOG_FILE"
echo "$vars" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"